
predefined_positions:
  fold_up:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    positions: [0.0, 1.57, -1.56, 0.0, -3.14, 0.0]
  extend:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    positions: [0.0, 1.57, 1.56, 0.0, 0.0, 0.0]
  extend_forward:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    positions: [0.0, 0.0, 1.56, 0.0, 0.0, 0.0]
  extend_backward:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    positions: [-3.1, 0.0, 1.56, 0.0, 0.0, 0.0]
  extend_backward_down:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    positions: [-3.1, -0.3, 1.56, 0.0, 0.0, 0.0]

  extend_forward_down:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    positions: [0.0, -0.3, 1.56, 0.0, 0.0, 0.0]

  deploy:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    positions: [0.0, 0.7853, -0.7853, 0.0, -1.57, 0.0]

predefined_trajectories:
  say_hi:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    points:
      - positions: [0.0, 0.9, 0.7, 0.0, -1.6, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 2.0, nsecs: 0.0}
      - positions: [0.0, 0.7, 0.4, 0.0, -1.3, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 4.0, nsecs: 0.0}
      - positions: [0.0, 1.1, 1.0, 0.0, -1.9, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 7.0, nsecs: 0.0}
      - positions: [0.0, 0.7, 0.4, 0.0, -1.3, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 10.0, nsecs: 0.0}
      - positions: [0.0, 1.1, 1.0, 0.0, -1.9, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 13.0, nsecs: 0.0}
      - positions: [0.0, 0.9, 0.7, 0.0, -1.6, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 15.0, nsecs: 0.0}

  unfold:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    points:
      - positions: [-3.11, -0.05, -1.51, -1.57, -3.1, 1.9]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 1.0, nsecs: 0.0}
      - positions: [-2.12, 0.370, -0.97, -1.41, -2.61, 2.035]
        velocities: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        time_from_start: {secs: 3.0, nsecs: 0.0}
      - positions: [-1.53, 0.824, -0.72, -1.70, -1.61, 0.358]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 6.0, nsecs: 0.0}
      
  fold:
    joint_names:
      - "girona1000/bravo/joint1"
      - "girona1000/bravo/joint2"
      - "girona1000/bravo/joint3"
      - "girona1000/bravo/joint4"
      - "girona1000/bravo/joint5"
      - "girona1000/bravo/joint6"
    points:
      - positions: [-1.53, 0.824, -0.72, -1.70, -1.61, 0.358]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 4.0, nsecs: 0.0}
      - positions: [-2.12, 0.370, -0.97, -1.41, -2.61, 2.035]
        velocities: [-0.1, -0.1, -0.1, 0.1, -0.1, 0.1]
        time_from_start: {secs: 8.0, nsecs: 0.0}
      - positions: [-3.11, -0.05, -1.51, -1.57, -3.1, 1.9]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 13.0, nsecs: 0.0}

  unfold_drill:
      joint_names:
        - "girona1000/bravo/joint1"
        - "girona1000/bravo/joint2"
        - "girona1000/bravo/joint3"
        - "girona1000/bravo/joint4"
        - "girona1000/bravo/joint5"
        - "girona1000/bravo/joint6"
      points:
        - positions: [-2.909, 0.3847, -1.109, -0.018, -2.280, -2.516]
          velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          time_from_start: {secs: 3.0, nsecs: 0.0}
        - positions: [-2.261, 0.2355, 0.0459, -0.143, -1.298, -2.757]
          velocities: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
          time_from_start: {secs: 6.0, nsecs: 0.0}
        - positions: [-2.254, 0.2383, 0.3522, -2.346, -1.986, -2.478]
          velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          time_from_start: {secs: 10.0, nsecs: 0.0}

  fold_drill:
      joint_names:
        - "girona1000/bravo/joint1"
        - "girona1000/bravo/joint2"
        - "girona1000/bravo/joint3"
        - "girona1000/bravo/joint4"
        - "girona1000/bravo/joint5"
        - "girona1000/bravo/joint6"
      points:
        - positions: [-2.254, 0.2383, 0.3522, -2.346, -1.986, -2.478]
          velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          time_from_start: {secs: 3.0, nsecs: 0.0}
        - positions: [-2.261, 0.2355, 0.0459, -0.143, -1.298, -2.757]
          velocities: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
          time_from_start: {secs: 7.0, nsecs: 0.0}
        - positions: [-2.909, 0.3847, -1.109, -0.018, -2.280, -2.516]
          velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          time_from_start: {secs: 10.0, nsecs: 0.0}

  fold_up_drill:
      joint_names:
        - "girona1000/bravo/joint1"
        - "girona1000/bravo/joint2"
        - "girona1000/bravo/joint3"
        - "girona1000/bravo/joint4"
        - "girona1000/bravo/joint5"
        - "girona1000/bravo/joint6"
      points:
        - positions: [0.144, 0.744, -0.63, 0.033, -1.49, -2.86]
          velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          time_from_start: {secs: 10.0, nsecs: 0.0}
        - positions: [0.157, 0.721, -0.50, 0.033, -2.92, -2.95]
          velocities: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
          time_from_start: {secs: 20.0, nsecs: 0.0}
        - positions: [0.157, 1.570, -0.50, 0.034, -2.92, -2.95]
          velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          time_from_start: {secs: 30.0, nsecs: 0.0}