# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Gripper Controllers ---------------------------------------
#gripper_position_controller:
#  type: velocity_controllers/JointPositionController
#  joint: girona1000/bravo/push_rod
#  pid:
#    p: 1.0
#    i: 0.0
#    d: 0.0
#
#gripper_velocity_controller:
#  type: velocity_controllers/JointVelocityController
#  joint: girona1000/bravo/push_rod

# Joint Controller -----------------------------------------
joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - girona1000/bravo/joint1
    - girona1000/bravo/joint2
    - girona1000/bravo/joint3
    - girona1000/bravo/joint4
    - girona1000/bravo/joint5
    - girona1000/bravo/joint6

joint_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - girona1000/bravo/joint1
    - girona1000/bravo/joint2
    - girona1000/bravo/joint3
    - girona1000/bravo/joint4
    - girona1000/bravo/joint5
    - girona1000/bravo/joint6
  gains:
    girona1000/bravo/joint1: { p: 5.0, i: 0.0, d: 0.0, i_clamp_min: -1, i_clamp_max: 1 }
    girona1000/bravo/joint2: { p: 5.0, i: 0.0, d: 0.0, i_clamp_min: -1, i_clamp_max: 1 }
    girona1000/bravo/joint3: { p: 5.0, i: 0.0, d: 0.0, i_clamp_min: -1, i_clamp_max: 1 }
    girona1000/bravo/joint4: { p: 5.0, i: 0.0, d: 0.0, i_clamp_min: -1, i_clamp_max: 1 }
    girona1000/bravo/joint5: { p: 5.0, i: 0.0, d: 0.2, i_clamp_min: -1, i_clamp_max: 1 }
    girona1000/bravo/joint6: { p: 5.0, i: 0.0, d: 0.2, i_clamp_min: -1, i_clamp_max: 1 }

  constraints:
    goal_time: 0.5                   
    stopped_velocity_tolerance: 0.001 
    girona1000/bravo/joint1: { trajectory: 0.05, goal: 0.05 }
    girona1000/bravo/joint2: { trajectory: 0.05, goal: 0.05 }
    girona1000/bravo/joint3: { trajectory: 0.05, goal: 0.05 }
    girona1000/bravo/joint4: { trajectory: 0.05, goal: 0.05 }      
    girona1000/bravo/joint5: { trajectory: 0.05, goal: 0.05 }
    girona1000/bravo/joint6: { trajectory: 0.05, goal: 0.05 }


joint1_position_controller:
  type: velocity_controllers/JointPositionController
  joint: girona1000/bravo/joint1
  pid:
    p: 5.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint2_position_controller:
  type: velocity_controllers/JointPositionController
  joint: girona1000/bravo/joint2
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint3_position_controller:
  type: velocity_controllers/JointPositionController
  joint: girona1000/bravo/joint3
  pid:
    p: 5.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint4_position_controller:
  type: velocity_controllers/JointPositionController
  joint: girona1000/bravo/joint4
  pid:
    p: 5.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint5_position_controller:
  type: velocity_controllers/JointPositionController
  joint: girona1000/bravo/joint5
  pid:
    p: 5.0
    i: 0.0
    d: 0.2
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint6_position_controller:
  type: velocity_controllers/JointPositionController
  joint: girona1000/bravo/joint6
  pid:
    p: 5.0
    i: 0.0
    d: 0.2
    i_clamp_min: -1.0
    i_clamp_max: 1.0


