vector28:
  - -128.3241400000001
  - 0
  - 0
  - 0
  - 8.0654
  - 0
  - 0
  - 0
  - 1.3426
  - 0
  - 0
  - 0
  - 6.3602
  - 0
  - 0
  - 0
  - 6.085799999999999
  - 0
  - 0
  - 0
  - 5.390000000000001
  - 0
  - 0
  - 0
  - 39.13140000000001
  - 0
  - 0
  - 0
