params:
  - -158.7188316710519
  - -63.16934557853693
  - 3.712152186978232
  - 155.7030519397577
  - 6.431823546964278
  - -1.318437545301802
  - 0.003477950832976682
  - 155.7060546993294
  - 10.14303796842899
  - -6.865411919593599
  - 0.1175710903577091
  - -0.003629906018340986
  - 13.16538434420032
  - -0.5475328875685467
  - 1.119435978998885
  - -0.003585058877312654
  - 12.7600775974586
  - 0.5143141355356964
  - -0.0149708606434801
  - -1.119507988866895
  - 11.97275298403724
  - -0.3154646964221239
  - -3.330341987339943
  - -0.014957863756293
  - 45.99569979754489
  - 1.400223930353464
  - 0.03583467582028784
  - 3.330337272080527
