vector28:
  - -136.7324026657409
  - -30
  - 11.77508081872851
  - 30
  - -21.9346
  - -18.23539929077423
  - -0.5987688617609501
  - 30
  - 10.13947927204289
  - -6.667600004756444
  - -1.496575034173791
  - 0.5983992162370535
  - 17.94956922562121
  - -2.038573882960573
  - 2.144389239636807
  - 0.597260111216504
  - 14.01179175371324
  - 3.894906831081872
  - -1.492497127389166
  - -2.145648466250295
  - 13.09831692380325
  - -2.579745569404548
  - -2.058502051608806
  - -1.492491363900775
  - 45.01887720397998
  - 1.091047856429195
  - 1.258935175815006
  - 2.058261083705936
