tcm:
  rows: 6
  cols: 6
  data:
  - - -0.7073882691671998
    - -0.7073882691671998
    - 0.7073882691647092
    - 0.7073882691647092
    - -4.148277390345741e-08
    - -4.148277390345741e-08
  - - 0.706825181105366
    - -0.706825181105366
    - 0.7068251811028774
    - -0.7068251811028774
    - 0.00020367319947071309
    - -0.00020367319947071309
  - - 0.0
    - 0.0
    - 2.65358979335273e-06
    - 2.65358979335273e-06
    - -0.9999999792586128
    - -0.9999999792586128
  - - -0.11309202897685855
    - 0.11309202897685855
    - -0.11309258516888107
    - 0.11309258516888107
    - 2.4644457135956283e-05
    - -2.4644457135956283e-05
  - - -0.11318212306675196
    - -0.11318212306675196
    - 0.11318058610714517
    - 0.11318058610714517
    - 0.5585999934332768
    - -0.5585999833944455
  - - -0.5576617261136732
    - 0.5576617261136732
    - 0.5576617261117096
    - -0.5576617261117096
    - 0.00011377184922434032
    - 0.00011377184922434032
